import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const Icon = ({ name, size = 20 }) => {
  const paths = {
    phone: <path d="M21 15.5v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.64-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 1.1 2.75 2 2 0 0 1 3.1.57h3a2 2 0 0 1 2 1.72c.13 1 .36 1.97.7 2.92a2 2 0 0 1-.45 2.11L7.08 8.6a16 16 0 0 0 6 6l1.28-1.27a2 2 0 0 1 2.11-.45c.94.34 1.92.57 2.91.7A2 2 0 0 1 21 15.5Z" />,
    arrow: <><path d="M5 12h14" /><path d="m13 6 6 6-6 6" /></>, check: <path d="m5 12 4.2 4L19 6.5" />,
    shield: <><path d="M12 3 20 6v5c0 5-3.4 8.3-8 10-4.6-1.7-8-5-8-10V6l8-3Z" /><path d="m8.7 12 2.1 2.1 4.5-4.4" /></>,
    money: <><rect x="3" y="5" width="18" height="14" rx="2" /><circle cx="12" cy="12" r="2.8" /></>, car: <><path d="m4 15 2.1-5.5A3 3 0 0 1 9 7.5h6a3 3 0 0 1 2.8 2L20 15v4H4v-4Z" /><path d="M3 19h18M7.5 19v2M16.5 19v2M7 14h.01M17 14h.01" /></>,
    map: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z" /><circle cx="12" cy="10" r="2.3" /></>, star: <path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.8-5.4 2.8 1-6.1L3.2 9.4l6.1-.9L12 3Z" />, plus: <><path d="M12 5v14M5 12h14" /></>, calc: <><path d="M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z" /><path d="M7 7h10M7 12h.01M12 12h.01M17 12h.01M7 17h.01M12 17h.01M17 17h.01" /></>, menu: <><path d="M4 7h16M4 12h16M4 17h16" /></>, close: <><path d="m6 6 12 12M18 6 6 18" /></>, clock: <><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3.2 1.9" /></>
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

const scenarios = [
  { slug: 'avto-v-kredite', title: 'Авто в кредите', short: 'Поможем закрыть кредит и оформить сделку безопасно.', problem: 'Кредит ещё не погашен, а автомобиль нужно продать быстро.', action: 'Предварительно уточним банк и остаток задолженности, объясним порядок расчёта и подготовим сделку.', docs: ['Паспорт', 'СТС', 'ПТС или ЭПТС', 'Кредитный договор'] },
  { slug: 'avto-v-zaloge', title: 'Авто в залоге', short: 'Подскажем порядок действий и оценим автомобиль.', problem: 'Автомобиль находится в залоге и требует корректного оформления.', action: 'Проверим доступный порядок снятия обременения и согласуем безопасный сценарий продажи.', docs: ['Паспорт', 'СТС', 'ПТС или ЭПТС', 'Данные о залоге'] },
  { slug: 'bitye-avto', title: 'Битое авто', short: 'Выкупим после ДТП, организуем эвакуатор при необходимости.', problem: 'Автомобиль после ДТП сложно продать самостоятельно.', action: 'Оценим повреждения по фото и при осмотре, при необходимости организуем эвакуатор.', docs: ['Паспорт', 'СТС', 'ПТС или ЭПТС'] },
  { slug: 'ne-na-hodu', title: 'Авто не на ходу', short: 'Приедем сами — выезд по Екатеринбургу бесплатно.', problem: 'Автомобиль не может самостоятельно приехать на осмотр.', action: 'Выезжаем к автомобилю в пределах Екатеринбурга и согласовываем способ транспортировки.', docs: ['Паспорт', 'СТС', 'ПТС или ЭПТС'] },
  { slug: 'starye-avto', title: 'Старые авто', short: 'Рассмотрим авто любого года выпуска и состояния.', problem: 'Продажа старого автомобиля через объявления занимает много времени.', action: 'Оценим комплектацию, состояние и документы — без необходимости готовить автомобиль к продаже.', docs: ['Паспорт', 'СТС', 'ПТС или ЭПТС'] },
]
const reviews = [['Алексей В.', 'Toyota Camry · 2015', 'Продал машину в тот же день. Оценщик приехал вовремя, сумму объяснили по пунктам, расчёт сразу после договора.'], ['Марина К.', 'Kia Rio · 2018', 'Нужно было срочно закрыть кредит. Менеджер всё спокойно разъяснил и помог с документами.'], ['Илья С.', 'Lada Granta · 2013', 'Авто было после ДТП и не на ходу. Забрали эвакуатором, никаких доплат за выезд не попросили.']]
const faqs = [['Как быстро вы получите автомобиль?', 'После согласования цены обычно выезжаем в день обращения. Осмотр занимает около 30 минут.'], ['Какие документы нужны?', 'Паспорт собственника, СТС и ПТС/ЭПТС. Для кредитного или залогового автомобиля список уточнит менеджер.'], ['Есть ли скрытые комиссии?', 'Нет. До выезда объясняем параметры оценки, а итоговая сумма фиксируется в договоре.'], ['Можно продать битый или неисправный автомобиль?', 'Да. Оценим автомобиль после ДТП, с техническими неисправностями или без возможности передвигаться самостоятельно.'], ['Почему итоговая сумма может отличаться от предварительной?', 'Предварительная оценка строится по вашим ответам. На итог влияют комплектация, состояние, документы и рынок.']]

function Layout({ children }) {
  const [menu, setMenu] = useState(false)
  return <><header className="header"><a className="logo" href="/"><span className="logo-mark"><Icon name="car" size={22} /></span><span>Авто <b>в Деньги</b></span></a><nav className={menu ? 'nav nav-open' : 'nav'}><a href="/how-we-work">Как работаем</a><a href="/scenarios">Сценарии</a><a href="/reviews">Отзывы</a><a href="/faq">Вопросы</a><a href="/contacts">Контакты</a></nav><div className="header-contact"><a href="tel:+73432889900">+7 (343) 288-99-00</a><span>Екатеринбург · ежедневно 8:00–22:00</span></div><button className="menu" onClick={() => setMenu(!menu)} aria-label="Открыть меню"><Icon name={menu ? 'close' : 'menu'} /></button></header>{children}<footer><a className="logo" href="/"><span className="logo-mark"><Icon name="car" size={22} /></span><span>Авто <b>в Деньги</b></span></a><span>© {new Date().getFullYear()} Авто в Деньги</span><a href="/privacy">Политика обработки данных</a></footer></>
}
function Page({ title, children, description }) { useEffect(() => { document.title = `${title} — Авто в Деньги`; const m = document.querySelector('meta[name="description"]'); if (m && description) m.content = description }, [title, description]); return <Layout>{children}</Layout> }
const CTA = ({ light = false }) => <a className={light ? 'btn btn-white' : 'btn btn-main'} href="/quiz">Получить оценку <Icon name="arrow" /></a>

function Home() { return <Page title="Срочный выкуп авто в Екатеринбурге" description="Срочный выкуп автомобилей в Екатеринбурге. Предварительная оценка за 2 минуты, выезд и деньги в день обращения."><main><section className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span/>Срочный выкуп авто в Екатеринбурге</div><h1>Продайте автомобиль <em>сегодня</em></h1><p className="hero-lead">Предварительная оценка за 2 минуты. Выезд, оформление и деньги — в день обращения.</p><div className="hero-actions"><CTA/><a className="btn btn-ghost" href="tel:+73432889900"><Icon name="phone"/>Позвонить</a></div><div className="hero-points"><span><Icon name="check"/>Без скрытых комиссий</span><span><Icon name="check"/>Бесплатный выезд</span><span><Icon name="check"/>Договор и расчёт сразу</span></div></div><CarArt/></section><Trust/><section className="section-pad benefit-section"><SectionHead kicker="Без лишних ожиданий" title="Всё, чтобы продать авто спокойно" text="Собираем данные заранее, чтобы назвать реалистичную сумму и не тратить ваше время на ненужные встречи."/><div className="benefits"><Benefit icon="calc" title="Понятная оценка" text="Объясняем, что влияет на цену: состояние, комплектация, документы и рынок."/><Benefit icon="shield" title="Безопасная сделка" text="Проверяем документы, оформляем договор и рассчитываемся сразу после оформления."/><Benefit icon="money" title="Деньги в день обращения" text="Наличными или переводом — удобный способ расчёта выбираете вы."/></div></section><section className="quiz-banner section-pad"><div><p className="kicker kicker-light">Предварительная оценка</p><h2>Расскажите об авто —<br/>мы подготовим расчёт</h2><p>Шесть коротких вопросов. Точная сумма — после разговора с менеджером или осмотра.</p></div><CTA light/></section><section className="section-pad scenarios"><SectionHead kicker="Любая ситуация" title={<>Выкупаем автомобили<br/>с особенностями</>} link="/scenarios" linkText="Все сценарии"/><ScenarioCards limit={5}/></section><section className="process section-pad"><div className="process-intro"><p className="kicker kicker-light">Как это работает</p><h2>Простой путь от заявки до денег</h2><p>Сначала понимаем ваш автомобиль, затем согласовываем удобный формат сделки.</p><CTA/></div><Steps/></section><section className="section-pad reviews"><SectionHead kicker="Опыт клиентов" title={<>Нас выбирают за ясность<br/>и скорость</>} link="/reviews" linkText="Все отзывы"/><ReviewCards limit={3}/></section></main></Page> }
function CarArt() { return <div className="hero-art" aria-label="Иллюстрация автомобиля"><div className="paint paint-a"/><div className="paint paint-b"/><div className="location-tag"><Icon name="map" size={16}/><span>Работаем по Екатеринбургу</span></div><div className="car-scene"><div className="car-body"><i/><i/><b/><b/></div><div className="car-shadow"/></div><div className="hero-card"><div className="card-icon"><Icon name="clock"/></div><div><small>Среднее время ответа</small><strong>15 минут</strong></div></div></div> }
function Trust(){return <section className="trustbar"><div><strong>10+ лет</strong><span>на рынке выкупа</span></div><div><strong>4,9 / 5</strong><span>оценка клиентов</span></div><div><strong>1 500+</strong><span>автомобилей выкуплено</span></div><div><strong>0 ₽</strong><span>за выезд и оценку</span></div></section>}
function SectionHead({ kicker, title, text, link, linkText }) { return <div className="section-head"><div><p className="kicker">{kicker}</p><h2>{title}</h2></div>{text && <p>{text}</p>}{link && <a className="text-link" href={link}>{linkText}<Icon name="arrow"/></a>}</div> }
function Benefit({icon,title,text}){return <article><div className="line-icon"><Icon name={icon}/></div><h3>{title}</h3><p>{text}</p></article>}
function ScenarioCards({ limit }) { return <div className="scenario-grid">{scenarios.slice(0, limit).map((s,i) => <article className={'scenario s'+i} key={s.slug}><span>{i === 0 ? 'Кредит' : i === 1 ? 'Залог' : i === 2 ? 'ДТП' : i === 3 ? 'Выезд' : 'Любой год'}</span><h3>{s.title}</h3><p>{s.short}</p><a href={`/scenarios/${s.slug}`}>Подробнее <Icon name="arrow" size={17}/></a></article>)}</div>}
function Steps(){return <div className="steps">{[['01','Расскажите об авто','Пройдите короткий квиз или позвоните нам.'],['02','Получите оценку','Менеджер уточнит детали и назовёт предварительную сумму.'],['03','Встретьтесь с оценщиком','Приедем в удобное место в Екатеринбурге.'],['04','Оформите сделку','Подписываем договор и сразу рассчитываемся.']].map(([n,t,p])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{p}</p></div></article>)}</div>}
function ReviewCards({limit}){return <div className="review-grid">{reviews.slice(0,limit).map(([name,car,quote])=><article key={name}><div className="review-top"><div className="avatar">{name[0]}</div><div><h3>{name}</h3><span>{car}</span></div><div className="stars">★★★★★</div></div><p>«{quote}»</p></article>)}</div>}

const quizSteps = [{title:'Какая у вас марка и модель?',hint:'Например: Toyota Camry',field:'model',placeholder:'Марка и модель'},{title:'Укажите год выпуска',hint:'Это влияет на предварительную оценку',field:'year',placeholder:'Например: 2018',type:'number'},{title:'Какой пробег?',hint:'Можно указать приблизительно',field:'mileage',placeholder:'Например: 120 000 км'},{title:'В каком состоянии автомобиль?',hint:'Выберите наиболее подходящий вариант',field:'condition',options:['Отличное','Хорошее','Есть замечания','После ДТП']},{title:'Есть особенности сделки?',hint:'Выберите всё, что относится к автомобилю',field:'features',options:['Нет особенностей','Кредит','Залог','Не на ходу']},{title:'Куда отправить расчёт?',hint:'Свяжемся в течение 15 минут в рабочее время',field:'contact',final:true}]
function Quiz(){const [step,setStep]=useState(0),[answers,setAnswers]=useState({}),[sent,setSent]=useState(false);const current=quizSteps[step], set=(f,v)=>setAnswers(a=>({...a,[f]:v}));return <Page title="Квиз оценки автомобиля"><main className="quiz-page"><div className="crumb"><a href="/">Главная</a> / Предварительная оценка</div><section className="quiz-layout"><div className="quiz-aside"><p className="kicker kicker-light">Предварительная оценка</p><h1>Узнайте сумму выкупа за 2 минуты</h1><p>Ответьте на несколько вопросов. Итоговую сумму назовём после короткого разговора или осмотра автомобиля.</p><div><Icon name="shield"/> Данные нужны только для подготовки оценки</div></div><div className="quiz-modal quiz-card">{sent?<div className="quiz-success"><div className="success-icon"><Icon name="check" size={30}/></div><p className="kicker">Заявка отправлена</p><h2>Спасибо за ответы!</h2><p>Менеджер подготовит предварительную оценку и свяжется с вами в рабочее время.</p><a className="btn btn-main" href="/">Вернуться на сайт</a></div>:<><div className="quiz-top"><span>Оценка автомобиля</span><b>{step+1} / {quizSteps.length}</b></div><div className="progress"><i style={{width:`${(step+1)/quizSteps.length*100}%`}}/></div><div className="quiz-question"><p>Шаг {step+1}</p><h2>{current.title}</h2><span>{current.hint}</span>{current.options?<div className="option-list">{current.options.map(o=><button className={answers[current.field]===o?'selected':''} onClick={()=>set(current.field,o)} key={o}>{o}<span className="radio"/></button>)}</div>:current.final?<div className="contact-fields"><input placeholder="Ваше имя" onChange={e=>set('name',e.target.value)}/><input type="tel" placeholder="Телефон +7 (___) ___-__-__" onChange={e=>set('phone',e.target.value)}/><select onChange={e=>set('method',e.target.value)}><option>Удобный способ связи</option><option>Звонок</option><option>WhatsApp</option><option>Telegram</option></select><label className="agreement"><input type="checkbox"/>Я согласен на обработку персональных данных</label></div>:<input type={current.type||'text'} placeholder={current.placeholder} onChange={e=>set(current.field,e.target.value)}/>}</div><div className="quiz-actions">{step>0&&<button className="back-btn" onClick={()=>setStep(step-1)}>Назад</button>}<button className="btn btn-main" disabled={!current.final&&!answers[current.field]} onClick={()=>step<5?setStep(step+1):setSent(true)}>{current.final?'Получить расчёт':'Продолжить'} <Icon name="arrow"/></button></div></>}</div></section></main></Page>}
function Scenarios(){return <Page title="Сценарии выкупа автомобилей"><HeroTitle kicker="Сценарии выкупа" title="Выкуп автомобиля в любой ситуации" text="Для каждого случая — отдельный порядок оценки, список документов и понятный следующий шаг."/><section className="section-pad scenarios list-page"><ScenarioCards limit={5}/></section><CTASection/></Page>}
function ScenarioPage({scenario}){return <Page title={`${scenario.title} в Екатеринбурге`}><HeroTitle kicker="Сценарии выкупа" title={`${scenario.title} в Екатеринбурге`} text={scenario.short}/><main><section className="section-pad detail-grid"><article><p className="kicker">Ситуация</p><h2>{scenario.problem}</h2><p>{scenario.action}</p></article><article className="document-card"><p className="kicker">Подготовьте заранее</p><h3>Документы для оценки</h3><ul>{scenario.docs.map(d=><li key={d}><Icon name="check" size={17}/>{d}</li>)}</ul><a href="/quiz" className="btn btn-main">Получить оценку <Icon name="arrow"/></a></article></section><section className="section-pad"><SectionHead kicker="Понятный порядок" title="Как проходит выкуп"/><div className="light-steps"><article><b>1</b><h3>Оценка</h3><p>Собираем сведения и ориентируем по предварительной сумме.</p></article><article><b>2</b><h3>Осмотр</h3><p>Сверяем состояние, документы и комплектацию автомобиля.</p></article><article><b>3</b><h3>Расчёт</h3><p>Оформляем договор и передаём деньги удобным способом.</p></article></div></section><FAQPreview/></main></Page>}
function How(){return <Page title="Как мы работаем"><HeroTitle kicker="Процесс сделки" title="Как проходит срочный выкуп автомобиля" text="От первой заявки до расчёта — без сложного калькулятора и неопределённости."/><main><section className="process section-pad"><div className="process-intro"><p className="kicker kicker-light">4 этапа</p><h2>От заявки до денег</h2><p>Менеджер остаётся на связи и заранее объясняет, какие данные нужны для каждого этапа.</p><CTA/></div><Steps/></section><section className="section-pad detail-grid"><article><p className="kicker">Что влияет на цену</p><h2>Сумму оцениваем прозрачно</h2><p>Учитываем модель, год, комплектацию, пробег, состояние кузова и техники, документы и текущий спрос на рынке.</p></article><article><p className="kicker">При осмотре</p><h2>Никаких неожиданных условий</h2><p>Финальную сумму называем после проверки автомобиля. Если условия не подходят, вы вправе отказаться от сделки.</p></article></section></main></Page>}
function Reviews(){return <Page title="Отзывы клиентов"><HeroTitle kicker="Отзывы" title="Опыт клиентов" text="Публикуем только подтверждённые отзывы и материалы, на которые есть разрешение клиента."/><main><section className="section-pad reviews review-page"><div className="review-filter"><button className="selected">Все автомобили</button><button>После ДТП</button><button>В кредите</button><button>Не на ходу</button></div><ReviewCards limit={3}/><p className="proof-note">Перед запуском необходимо заменить демонстрационные отзывы на реальные: с разрешением на публикацию, скриншотами или фото сделки.</p></section></main></Page>}
function About(){return <Page title="О компании"><HeroTitle kicker="О компании" title="Сервис срочного выкупа авто в Екатеринбурге" text="Наша задача — сделать оценку и сделку понятными: без скрытых комиссий, с договором и расчётом в день обращения."/><main><section className="section-pad about-grid"><div className="about-photo"><Icon name="car" size={50}/><span>Фото команды и точки осмотра</span></div><div><p className="kicker">Открытость</p><h2>Доверие строится на деталях</h2><p>На странице компании должны быть опубликованы реальные реквизиты, фотографии команды и точки осмотра, зона выезда, документы и актуальные контакты.</p><a className="btn btn-main" href="/contacts">Связаться с нами <Icon name="arrow"/></a></div></section><section className="section-pad requisites"><p className="kicker">Юридическая информация</p><h2>Реквизиты компании</h2><p>Здесь размещаются ИНН, ОГРН, наименование юридического лица и договорные документы после передачи фактических данных компании.</p></section></main></Page>}
function FAQ(){const [open,setOpen]=useState(null);return <Page title="Частые вопросы"><HeroTitle kicker="FAQ" title="Отвечаем на частые вопросы" text="Разбираем сроки, документы, кредит, залог, эвакуатор, комиссию и безопасность сделки."/><main><section className="section-pad faq one-column"><div className="faq-list">{faqs.map(([q,a],i)=><article className={open===i?'faq-open':''} key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><Icon name="plus"/></button>{open===i&&<p>{a}</p>}</article>)}</div></section></main></Page>}
function Contacts(){const [sent,setSent]=useState(false);return <Page title="Контакты"><main className="contacts contacts-page"><div className="contact-copy"><p className="kicker kicker-light">Связаться с нами</p><h1>Оценим ваш автомобиль уже сегодня</h1><p>Оставьте номер — менеджер перезвонит в течение 15 минут в рабочее время.</p><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Ваш телефон<input required type="tel" placeholder="+7 (___) ___-__-__"/></label><button className="btn btn-main">Получить звонок <Icon name="arrow"/></button><small>Отправляя форму, вы соглашаетесь на обработку персональных данных.</small></form>{sent&&<div className="success">Спасибо! Мы свяжемся с вами в ближайшее время.</div>}<div className="contact-links"><a href="tel:+73432889900"><Icon name="phone"/>+7 (343) 288-99-00</a><span><Icon name="clock"/>ежедневно 8:00–22:00</span></div></div><Map/></main></Page>}
function Map(){return <div className="map"><div className="map-grid"/><div className="map-pin"><Icon name="map"/><b>Авто в Деньги</b><span>Екатеринбург</span></div><div className="address"><strong>Екатеринбург</strong><span>Адрес точки осмотра уточняйте у менеджера</span><a href="tel:+73432889900">+7 (343) 288-99-00</a></div></div>}
const articles=[['kak-prodat-avto-v-kredite','Как продать автомобиль в кредите','Разбираем, какие данные подготовить и почему порядок сделки важно согласовать заранее.'],['vyкуп-bityh-avto','Выкуп битого автомобиля: что влияет на цену','Состояние, документы и возможность самостоятельного передвижения — ключевые данные для оценки.'],['kak-rabotaet-srochnyi-vykup','Как работает срочный выкуп авто','Чем предварительная оценка отличается от финальной и как проходит осмотр.']]
function Articles(){return <Page title="Статьи"><HeroTitle kicker="Полезные материалы" title="Всё о продаже автомобиля" text="Информационные статьи помогают заранее разобраться в процессе и принять взвешенное решение."/><main><section className="section-pad article-grid">{articles.map(([slug,title,text])=><article key={slug}><span>Полезные материалы</span><h2>{title}</h2><p>{text}</p><a className="text-link" href={`/articles/${slug}`}>Читать статью <Icon name="arrow"/></a></article>)}</section></main></Page>}
function Article({data}){return <Page title={data[1]}><main className="article"><div className="crumb"><a href="/">Главная</a> / <a href="/articles">Статьи</a> / {data[1]}</div><span className="kicker">Полезные материалы</span><h1>{data[1]}</h1><p className="article-lead">{data[2]}</p><div className="article-body"><h2>Что важно учесть</h2><p>Перед обращением подготовьте сведения об автомобиле: марку и модель, год, пробег, состояние, особенности документов и удобный способ связи. Это позволит назвать реалистичную предварительную оценку.</p><h2>Как проходит оценка</h2><p>Сначала менеджер уточняет детали. Финальная сумма определяется после осмотра автомобиля, проверки комплектации и документов. Все условия сделки обсуждаются до подписания договора.</p><a className="btn btn-main" href="/quiz">Получить оценку <Icon name="arrow"/></a></div></main></Page>}
function HeroTitle({kicker,title,text}){return <section className="inner-hero section-pad"><div><p className="kicker">{kicker}</p><h1>{title}</h1><p>{text}</p><CTA/></div></section>}
function FAQPreview(){return <section className="section-pad faq-preview"><SectionHead kicker="Вопросы" title="Частые вопросы" link="/faq" linkText="Все вопросы"/><div>{faqs.slice(0,3).map(([q,a])=><article key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></section>}
function CTASection(){return <section className="quiz-banner section-pad"><div><p className="kicker kicker-light">Предварительная оценка</p><h2>Готовы узнать сумму?</h2><p>Ответьте на шесть коротких вопросов — перезвоним с предварительным расчётом.</p></div><CTA light/></section>}
function Privacy(){return <Page title="Политика обработки данных"><main className="article"><h1>Политика обработки персональных данных</h1><div className="article-body"><p>Форма является демонстрационной. До публикации необходимо разместить утверждённую политику обработки персональных данных, сведения об операторе и механизм получения согласия.</p></div></main></Page>}

function Router(){const path=decodeURI(window.location.pathname).replace(/\/$/,'')||'/'; if(path==='/')return <Home/>; if(path==='/quiz')return <Quiz/>; if(path==='/scenarios')return <Scenarios/>; if(path.startsWith('/scenarios/')){const s=scenarios.find(x=>x.slug===path.split('/').pop());return s?<ScenarioPage scenario={s}/>:<Home/>} if(path==='/how-we-work')return <How/>;if(path==='/reviews')return <Reviews/>;if(path==='/about')return <About/>;if(path==='/faq')return <FAQ/>;if(path==='/contacts')return <Contacts/>;if(path==='/articles')return <Articles/>;if(path.startsWith('/articles/')){const a=articles.find(x=>x[0]===path.split('/').pop());return a?<Article data={a}/>:<Articles/>}if(path==='/privacy')return <Privacy/>;return <Home/>}

const structuredData={'@context':'https://schema.org','@graph':[{'@type':'LocalBusiness',name:'Авто в Деньги',telephone:'+7 (343) 288-99-00',address:{'@type':'PostalAddress',addressLocality:'Екатеринбург',addressCountry:'RU'},areaServed:'Екатеринбург'},{'@type':'FAQPage',mainEntity:faqs.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))}]}
document.head.insertAdjacentHTML('beforeend',`<script type="application/ld+json">${JSON.stringify(structuredData)}</script>`)
createRoot(document.getElementById('root')).render(<Router/>)
